url = 'https://github.com/pakket-project/builder/archive/refs/tags/v0.0.2.tar.gz'
supportsRosetta = false
[dependencies]
dependencies = []
buildDependencies = ['go']
optionalDependencies = []

[intel]
checksum = 'a8de17aab5edeaba7f0e17df2730c19863ade9cd0d3c9fab7b0578f12540aa9c'

[silicon]
checksum = '9118a5bb86537abde5e7009d009123dbdddc67fd0a77aeca2e574ed6e6043331'

