name: "test workflow aaah"

on:
  pull_request:
    types: [opened]
    paths:
      - "packages/**"
  push:
    paths:
      - "packages/**"

jobs:
  test:
    runs-on: "${{matrix.os}}"
    strategy:
      matrix:
        include:
          - os: ["self-hosted", "silicon"]
            shell: "/usr/bin/arch -arch arm64e /bin/bash --noprofile --norc -eo pipefail {0}"
          - os: ["self-hosted", "intel"]
            shell: "bash"

    defaults:
      run:
        shell: "${{matrix.shell}}"

    steps:
      - name: "check arch"
        run: "arch"

      - name: "checkout repository"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "setup pakket-builder"
        uses: pakket-project/actions/setup-builder@main

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v1.1.3

      - name: Run pakket-builder on all modified files
        run: |
          for file in "${{ steps.changed-files.outputs.all_modified_files }}"; do
            if [[ $file =~ (packages\/)([^\/]*)\/([^\/]*)\/([^\n]*) ]]
            then
                pakket-builder build "packages/${BASH_REMATCH[2]}" "${BASH_REMATCH[3]}" -o "${BASH_REMATCH[2]}-${BASH_REMATCH[3]}"

                echo $(ls "${BASH_REMATCH[2]}-${BASH_REMATCH[3]}")
            else
                echo "$file doesn't match" >&2 # this could get noisy if there are a lot of non-matching files
            fi
          done
