name: "test workflow aaah"

on: ["workflow_dispatch", "push"]

jobs:
  test:
    runs-on: "${{matrix.os}}"
    strategy:
      matrix:
        include:
          - os: ["self-hosted", "silicon"]
            shell: "/usr/bin/arch -arch arm64e /bin/bash --noprofile --norc -eo pipefail {0}"
          - os: ["self-hosted", "intel"]
            shell: "bash"

    defaults:
      run:
        shell: "${{matrix.shell}}"

    steps:
      - name: "set arm shell"
        if: "contains(matrix.os, 'silicon')"
        run: "/usr/bin/arch -arch arm64e /bin/bash"

      - name: "arch"
        run: "arch"

      - name: "checkout repository"
        uses: actions/checkout@v2

      - name: "setup pakket-builder"
        uses: pakket-project/actions/setup-builder@main

      - name: "run pakket-builder"
        run: "pakket-builder -h"
