name: "test workflow aaah"

on: ["workflow_dispatch", "push"]

jobs:
  test:
    runs-on: ["self-hosted", "silicon"]
    # strategy:
    #   matrix:
    #     include:
    #       - os: ["self-hosted", "silicon"]
    #       - os: ["self-hosted", "intel"]

    steps:
      # - run: "echo running on ${{matrix.os}}"

      - name: "setup pakket-builder"
        uses: pakket-project/test/setup-builder@main

      - name: "run pakket-builder"
        run: "pakket-builder -h"
