name: "test workflow aaah"

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number"
        default: "0"
        required: true
      version:
        description: "package version"
        default: "0.0.0"
        required: true

jobs:
  test:
    runs-on: "${{matrix.os}}"
    strategy:
      matrix:
        include:
          - os: ["self-hosted", "silicon"]
            shell: "/usr/bin/arch -arch arm64e /bin/bash --noprofile --norc -eo pipefail {0}"
          - os: ["self-hosted", "intel"]
            shell: "bash"

    defaults:
      run:
        shell: "${{matrix.shell}}"

    steps:
      - name: "check arch"
        run: "arch"

      - name: "checkout repository"
        uses: actions/checkout@v2

      - name: "setup pakket-builder"
        uses: pakket-project/actions/setup-builder@main

      - name: "run pakket-builder"
        run: "pakket-builder -h"

      - name: "ls"
        run: echo $(ls)
