name: "test workflow aaah"

on:
  pull_request:
    types: [opened]
    paths:
      - "packages/**"
  push:
    paths:
      - "packages/**"

jobs:
  test:
    runs-on: "${{matrix.os}}"
    strategy:
      matrix:
        include:
          - os: ["self-hosted", "silicon"]
            shell: "/usr/bin/arch -arch arm64e /bin/bash --noprofile --norc -eo pipefail {0}"
          - os: ["self-hosted", "intel"]
            shell: "bash"

    defaults:
      run:
        shell: "${{matrix.shell}}"

    steps:
      - name: "check arch"
        run: "arch"

      - name: "checkout repository"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "setup pakket-builder"
        uses: pakket-project/actions/setup-builder@main

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v1.1.3

      - name: "run pakket-builder"
        run: "pakket-builder -h"

      - name: List all modified files
        run: |
          for file in "${{ steps.changed-files.outputs.all_modified_files }}"; do
             file = $file | sed -e "s/^packages\///"
             echo $file
          done
