name: "test workflow aaah"

on: ["workflow_dispatch", "push"]

jobs:
  test:
    runs-on: macos-11
    steps:
      - name: "setup pakket-builder"
      - uses: pakket-project/test/setup-builder@main

      - name: "run pakket-builder"
      - run: "pakket-builder -h"
